#!/bin/sh
# Script to run `make` command inside a centos7 docker container
# Files generated by `make` will be written to the current directory on the host
# Execute the container using: sudo docker run --rm=true -e "USERID=${UID}" -v `pwd`:/src:rw centos:centos7 /bin/sh -c "cd src && ./deploy/make-on-centos7.sh"

# Add a default user to squash unknown user errors during rpmbuild
adduser --uid "${USERID}" hostuser

# Install dependencies
yum -y clean all
yum -y clean expire-cache
yum -y install rpm-build make git

# Run make command as the default user so that generated files aren't owned by root
su hostuser -c "make"
