name: RPM Packaging

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: RPM Packaging
    runs-on: ubuntu-22.04
    container: rockylinux:9
    steps:
      - name: Install Dependencies
        run: |
          cat /etc/redhat-release
          dnf -y install 'dnf-command(config-manager)'
          dnf -y config-manager --set-enabled crb
          dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
          yum -y install git rpm-build rpm-sign rsync make python3-rpm-macros systemd-rpm-macros pyproject-rpm-macros python3-devel python3-toml python3-wheel

      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Package RPMs
        run:
          make

      - name: Clone Package Repository
        uses: actions/checkout@v3
        with:
          repository: rockit-astro/packages
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: packages

      - name: Push Packages
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
        run:
          packages/sign-and-push-packages.sh *.rpm
