name: RPM Packaging

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: RPM Packaging
    runs-on: ubuntu-22.04
    container: rockylinux:9
    steps:
      - name: Install Dependencies
        run: |
          cat /etc/redhat-release
          yum -y install epel-release
          /usr/bin/crb enable
          yum -y install git rpm-build rpm-sign rsync make python3-rpm-macros pyproject-rpm-macros python3-devel python3-tomli systemd-rpm-macros python3-wheel

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Package RPMs
        run:
          make

      - name: Clone Package Repository
        uses: actions/checkout@v4
        with:
          repository: rockit-astro/packages
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: packages

      - name: Push Packages
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
        run:
          packages/sign-and-push-packages.sh *.rpm
